POST localhost:5088/parts/downloadammoseek
Content-Type: application/json

{
  "caliber": "224-valkyrie"
}

### Send POST request with json body
POST localhost:5088/parts/downloadrecordsfromairtable
Content-Type: application/json

{
  "limit": 5,
  "base_name": "allyourbasebelongtome"
}

###
PATCH localhost:5088/parts/importrecordstoneo4j
Content-Type: application/json

{
"base_name": "allyourbasebelongtome"
}

###
PATCH localhost:5088/parts/importrecordstoneo4jfromcsv
Content-Type: application/json

{
  "import_file_path": "/home/Downloads/Parts.csv"
}