// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace nugsnet6.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Build
    {
        
        public string Id { get; set; } = string.Empty;

        
        public DateTimeOffset CreatedTime { get; set; }

        
        public string Name { get; set; } = string.Empty;

        
        public string Reasoning { get; set; } = string.Empty;

        
        public string[] Parts { get; set; }

        
        public string[] Caliber { get; set; }

        
        public Pic[] Pics { get; set; }

        
        public double TotalCost { get; set; }

        
        public double Weight { get; set; }

        
        public DateTimeOffset Created { get; set; }

        
        public LastModifiedBy CreatedBy { get; set; }

        
        public DateTimeOffset LastModified { get; set; }

        
        public LastModifiedBy LastModifiedBy { get; set; }
    }

    public partial class LastModifiedBy
    {
        
        public string Id { get; set; } = string.Empty;

        
        public string Email { get; set; } = string.Empty;

        
        public string Name { get; set; } = string.Empty;
    }

    public partial class Pic
    {
        
        public string Id { get; set; } = string.Empty;

        
        public long Width { get; set; }

        
        public long Height { get; set; }

        
        public Uri Url { get; set; }

        
        public string Filename { get; set; } = string.Empty;

        
        public long Size { get; set; }

        
        public string Type { get; set; } = string.Empty;

        
        public Thumbnails Thumbnails { get; set; }
    }

    public partial class Thumbnails
    {
        
        public Full Small { get; set; }

        
        public Full Large { get; set; }

        
        public Full Full { get; set; }
    }

    public partial class Full
    {
        
        public Uri Url { get; set; }

        
        public long Width { get; set; }

        
        public long Height { get; set; }
    }

    // public partial class Build
    // {
    //     public static Build FromJson(string json) => JsonConvert.DeserializeObject<Build>(json, nugsnet6.Models.Builds.Converter.Settings);
    // }

    // public static class Serialize
    // {
    //     public static string ToJson(this Build self) => JsonConvert.SerializeObject(self, nugsnet6.Models.Builds.Converter.Settings);
    // }

    // public static class Converter
    // {
    //     public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //     {
    //         MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //         DateParseHandling = DateParseHandling.None,
    //         Converters = {
    //             new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //         },
    //     };
    // }
}
