// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace nugsnet6.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Build
    {
        //[JsonProperty("id")]
        public string Id { get; set; }

        //[JsonProperty("createdTime")]
        public DateTimeOffset CreatedTime { get; set; }

        //[JsonProperty("Name")]
        public string Name { get; set; }

        //[JsonProperty("Reasoning")]
        public string Reasoning { get; set; }

        //[JsonProperty("Parts")]
        public string[] Parts { get; set; }

        //[JsonProperty("Caliber")]
        public string[] Caliber { get; set; }

        //[JsonProperty("Pics")]
        public Pic[] Pics { get; set; }

        //[JsonProperty("Total Cost")]
        public double TotalCost { get; set; }

        //[JsonProperty("Weight")]
        public double Weight { get; set; }

        //[JsonProperty("Created")]
        public DateTimeOffset Created { get; set; }

        //[JsonProperty("Created By")]
        public LastModifiedBy CreatedBy { get; set; }

        //[JsonProperty("Last Modified")]
        public DateTimeOffset LastModified { get; set; }

        //[JsonProperty("Last Modified By")]
        public LastModifiedBy LastModifiedBy { get; set; }
    }

    public partial class LastModifiedBy
    {
        //[JsonProperty("id")]
        public string Id { get; set; }

        //[JsonProperty("email")]
        public string Email { get; set; }

        //[JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Pic
    {
        //[JsonProperty("id")]
        public string Id { get; set; }

        //[JsonProperty("width")]
        public long Width { get; set; }

        //[JsonProperty("height")]
        public long Height { get; set; }

        //[JsonProperty("url")]
        public Uri Url { get; set; }

        //[JsonProperty("filename")]
        public string Filename { get; set; }

        //[JsonProperty("size")]
        public long Size { get; set; }

        //[JsonProperty("type")]
        public string Type { get; set; }

        //[JsonProperty("thumbnails")]
        public Thumbnails Thumbnails { get; set; }
    }

    public partial class Thumbnails
    {
        //[JsonProperty("small")]
        public Full Small { get; set; }

        //[JsonProperty("large")]
        public Full Large { get; set; }

        //[JsonProperty("full")]
        public Full Full { get; set; }
    }

    public partial class Full
    {
        //[JsonProperty("url")]
        public Uri Url { get; set; }

        //[JsonProperty("width")]
        public long Width { get; set; }

        //[JsonProperty("height")]
        public long Height { get; set; }
    }

    // public partial class Build
    // {
    //     public static Build FromJson(string json) => JsonConvert.DeserializeObject<Build>(json, nugsnet6.Models.Builds.Converter.Settings);
    // }

    // public static class Serialize
    // {
    //     public static string ToJson(this Build self) => JsonConvert.SerializeObject(self, nugsnet6.Models.Builds.Converter.Settings);
    // }

    // public static class Converter
    // {
    //     public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //     {
    //         MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //         DateParseHandling = DateParseHandling.None,
    //         Converters = {
    //             new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //         },
    //     };
    // }
}
