// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace nugsnet6.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Loadout
    {
        //[JsonProperty("id")]
        public string Id { get; set; }

        //[JsonProperty("createdTime")]
        public DateTimeOffset CreatedTime { get; set; }

        // //[JsonProperty("Id")]
        // public long Id { get; set; }

        //[JsonProperty("Kit")]
        public string[] Kit { get; set; }

        //[JsonProperty("Primary Arm")]
        public string[] PrimaryArm { get; set; }

        //[JsonProperty("Name")]
        public string Name { get; set; }

        //[JsonProperty("Inspiration")]
        public Uri Inspiration { get; set; }

        //[JsonProperty("Sidearm")]
        public string[] Sidearm { get; set; }

        //[JsonProperty("URL (from Part)")]
        public Uri[] UrlFromPart { get; set; }

        // //[JsonProperty("Attachments (from Part)")]
        // public AttachmentsFromPart[] AttachmentsFromPart { get; set; }

        //[JsonProperty("Kit Cost")]
        public double[] KitCost { get; set; }

        //[JsonProperty("Name (from Part)")]
        public string[] NameFromPart { get; set; }

        //[JsonProperty("Combos (from Builds)")]
        public string[] CombosFromBuilds { get; set; }

        //[JsonProperty("Parts (from Builds)")]
        public string[] PartsFromBuilds { get; set; }

        //[JsonProperty("Name (from Builds)")]
        public string[] NameFromBuilds { get; set; }

        //[JsonProperty("Total_Cost")]
        public double TotalCost { get; set; }

        //[JsonProperty("Sidearm Cost")]
        public long[] SidearmCost { get; set; }

        //[JsonProperty("Primary Arm Cost")]
        public double[] PrimaryArmCost { get; set; }
    }

    // public partial class AttachmentsFromPart
    // {
    //     //[JsonProperty("id")]
    //     public string Id { get; set; }

    //     //[JsonProperty("width")]
    //     public long Width { get; set; }

    //     //[JsonProperty("height")]
    //     public long Height { get; set; }

    //     //[JsonProperty("url")]
    //     public Uri Url { get; set; }

    //     //[JsonProperty("filename")]
    //     public string Filename { get; set; }

    //     //[JsonProperty("size")]
    //     public long Size { get; set; }

    //     //[JsonProperty("type")]
    //     public string Type { get; set; }

    //     //[JsonProperty("thumbnails")]
    //     public Thumbnails Thumbnails { get; set; }
    // }

    // public partial class Thumbnails
    // {
    //     //[JsonProperty("small")]
    //     public Full Small { get; set; }

    //     //[JsonProperty("large")]
    //     public Full Large { get; set; }

    //     //[JsonProperty("full")]
    //     public Full Full { get; set; }
    // }

    // public partial class Full
    // {
    //     //[JsonProperty("url")]
    //     public Uri Url { get; set; }

    //     //[JsonProperty("width")]
    //     public long Width { get; set; }

    //     //[JsonProperty("height")]
    //     public long Height { get; set; }
    // }

    // public partial class Loadout
    // {
    //     public static Loadout FromJson(string json) => JsonConvert.DeserializeObject<Loadout>(json, nugsnet6.Models.Loadouts.Converter.Settings);
    // }

    // public static class Serialize
    // {
    //     public static string ToJson(this Loadout self) => JsonConvert.SerializeObject(self, nugsnet6.Models.Loadouts.Converter.Settings);
    // }

    // public static class Converter
    // {
    //     public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    //     {
    //         MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
    //         DateParseHandling = DateParseHandling.None,
    //         Converters = {
    //             new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
    //         },
    //     };
    // }
}
