// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

using CodeMechanic.Extensions;
using NSpecifications;
using nugsnet6.Experimental;

namespace nugsnet6;

public class Part
{
    public string Id { get; set; } = string.Empty;
    public DateTime createdTime { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Kind { get; set; } = string.Empty;
    public string Type { get; set; } = string.Empty;
    public string Notes { get; set; } = string.Empty;
    public string ProductCode { get; set; } = string.Empty;

    public double Cost { get; set; }
    public double WeightInOz { get; set; }
    public Attachment[] Attachments { get; set; }
    public string[] Calibers { set; get; }
    public string[] Builds { set; get; }
    public Uri Url { get; set; }
    public Uri Demo { get; set; }
    public long ComboCost { get; set; }
    public User CreatedBy { get; set; }
    public DateTimeOffset Created { get; set; }
    public object Combo { get; set; }
    public User LastModifiedBy { get; set; }
    public DateTimeOffset LastModified { get; set; }

    public static Maybe<Part> NotFound = new Maybe<Part>(new Part()
    {
        Id = string.Empty, Name = "Not Available", Cost = -1, ComboCost = -1
    });

    public static ISpecification<Part> IsValid => new Spec<Part>(part => part.Cost > 0
                                                                         && NotFound.IfSome(_ =>
                                                                             part.Equals(NotFound.Value)));
}

public sealed class User
{
    public string Id { get; set; } = string.Empty;

    public string Email { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;
    public Role Role { get; set; } = Role.Basic;
}

public class Attachment
{
    public string Id { get; set; } = string.Empty;


    // public long Width { get; set; }
    //
    //
    // public long Height { get; set; }
    //
    //
    // public Uri Url { get; set; }
    //
    //
    // public string Filename { get; set; } = string.Empty;
    //
    //
    // public long Size { get; set; }
    //
    //
    // public string Type { get; set; } = string.Empty;
    //
    // public Thumbnails Thumbnails { get; set; }
}

// public class Thumbnails
// {

//     public Full Small { get; set; }


//     public Full Large { get; set; }


//     public Full Full { get; set; }
// }

// public  class Full
// {

//     public Uri Url { get; set; }


//     public long Width { get; set; }


//     public long Height { get; set; }
// }